# Generated by Django 3.2.7 on 2021-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('dependents', models.IntegerField(max_length=2)),
                ('education', models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=15)),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('applicant_income', models.IntegerField(max_length=10)),
                ('co_applicant_income', models.FloatField(max_length=10)),
                ('loan_amount', models.FloatField(max_length=10)),
                ('loan_term', models.FloatField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('property_area', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural'), ('SemiUrban', 'SemiUrban')], max_length=10)),
            ],
        ),
    ]
