# Generated by Django 3.2.7 on 2021-09-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfeatures',
            name='applicant_income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='dependents',
            field=models.IntegerField(),
        ),
    ]
