# Generated by Django 3.2.7 on 2021-09-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0002_auto_20210901_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfeatures',
            name='education',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], default='Not Graduate', max_length=15),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='loan_term',
            field=models.FloatField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='married',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='property_area',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural'), ('SemiUrban', 'SemiUrban')], default='Urban', max_length=10),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='self_employed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
    ]
