# Generated by Django 3.2.7 on 2021-09-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0003_auto_20210901_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfeatures',
            name='loan_term',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
    ]
