# Generated by Django 3.2.7 on 2021-09-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0004_alter_modelfeatures_loan_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfeatures',
            name='applicant_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='co_applicant_income',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='dependents',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='education',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], default='Not Graduate', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='loan_amount',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='loan_term',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='property_area',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural'), ('SemiUrban', 'SemiUrban')], default='Urban', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='modelfeatures',
            name='self_employed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, null=True),
        ),
    ]
