# Generated by Django 3.2.7 on 2021-09-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0005_auto_20210902_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfeatures',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
