# Generated by Django 3.2.7 on 2021-09-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0006_alter_modelfeatures_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfeatures',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
